#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd -P)

link_file() {
    local src=$1 dst=$2

    # if dst exist, delete it
    if [ -f "$dst" -o "$dst" -o -L "$dst" ] 
    then
        # TODO: Ask user what to do
        rm -rf "$dst"
    fi

    ln -s "$src" "$dst"
    echo "$src -> $dst"
}

install_dotfiles () {
    echo "linking dotfiles..."

    local overwrite_all=false backup_all=false skip_all=false

    for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink') 
    do
        dst="$HOME/.$(basename "${src%.*}")"
        link_file "$src" "$dst"
    done

}

setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    echo 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    echo ' - What is your github author name?'
    read -e git_authorname
    echo ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    echo 'gitconfig'
  fi
}

install_dotfiles
setup_gitconfig
echo ''
echo 'done'