#!/usr/bin/env bash

DOTFILES_ROOT=$(pwd -P)

link_file() {
    local src=$1 dst=$2

    # if dst exist, delete it
    if [ -f "$dst" -o "$dst" -o -L "$dst" ] 
    then
        # TODO: Ask user what to do
        rm -rf "$dst"
    fi

    ln -s "$src" "$dst"
    echo "$src -> $dst"
}

install_dotfiles () {
    echo "linking dotfiles..."

    local overwrite_all=false backup_all=false skip_all=false

    for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink') 
    do
        dst="$HOME/.$(basename "${src%.*}")"
        link_file "$src" "$dst"
    done

}

install_dotfiles
echo ''
echo 'done'